version: '3.7'

services:

    client:
        build:
            context: .
        command: yarn start

        ports:
          - "3000:3000"
        volumes:
            - .:/usr/src/client
            - node_modules:/home/node/node_modules

volumes:
    node_modules:
